### ISSUE TITLE
Support for vue 2

### ISSUE THREAD

**Issue by drunkenvalley** [tobiasdiez/storybook-vue-addon#47]
I run into a straightforward issue when testing this addon: It appears to be unable to index.

```bash
WARN 🚨 Unable to index ./src/components/medium/PageList/PageList.stories.vue:
WARN   TypeError: Cannot read properties of undefined (reading 'template')
WARN     at parse (RedactedFilepath\node_modules\storybook-vue-addon\dist\storybook.cjs:157:18)
WARN     at indexerCode (RedactedFilepath\node_modules\storybook-vue-addon\dist\storybook.cjs:337:29)
WARN     at Object.indexer (RedactedFilepath\node_modules\storybook-vue-addon\dist\storybook.cjs:334:10)
WARN     at async StoryIndexGenerator.extractStories (RedactedFilepath\node_modules\@storybook\core-server\dist\index.js:13:3554)
WARN     at async RedactedFilepath\node_modules\@storybook\core-server\dist\index.js:13:1869
WARN     at async Promise.all (index 0)
WARN     at async Promise.all (index 2)
WARN     at async StoryIndexGenerator.updateExtracted (RedactedFilepath\node_modules\@storybook\core-server\dist\index.js:13:1641)
WARN     at async StoryIndexGenerator.ensureExtracted (RedactedFilepath\node_modules\@storybook\core-server\dist\index.js:13:2262)
WARN     at async StoryIndexGenerator.initialize (RedactedFilepath\node_modules\@storybook\core-server\dist\index.js:13:1568)
```

## `PageList.stories.vue`

```vue
<script setup>
import PageList from './PageList.vue'
import PageTeaser from '@/components/small/PageTeaser/PageTeaser.vue'
import img2021 from "@/assets/annualReport2021-sized.webp"
</script>
<template>
    <Stories title="Components/Medium/Page List" :component="PageList">
        <Story title="Primary">
            <PageList>
                <PageTeaser  alt="The annual report" aria-label="Related content Annual Report 2021" href="https://example.com" :src="img2021">
                    Annual Report 2021
                </PageTeaser>
            </PageList>
        </Story>
    </Stories>
</template>
```

## `main.ts`

```typescript
export default {
  stories: [
    '../src/frontpage.mdx',
    '../src/**/*.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx|vue)'
  ],
  staticDirs: [
    "../public"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "storybook-vue-addon",
    "@storybook/addon-mdx-gfm",
  ],
  framework: "@storybook/vue-vite",
  core: {
    disableTelemetry: true
  },
  features: {
    "storyStoreV7": true
  }
};
```

## `vite.config.ts`

```typescript
import { resolve } from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react"
import vue2 from '@vitejs/plugin-vue2'
import svgr from 'vite-plugin-svgr'

import VueStories from 'storybook-vue-addon/vite'

export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, "src/main.scss"),
      name: "Redacted",
      fileName: "Redacted",
    },
  },
  plugins: [
    react(),
    vue2(),
    VueStories({
      /* options */
    }),
    svgr({
      exportAsDefault: true
    })
  ],
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
      'vue': 'vue/dist/vue.esm.js'
    }
  }
});
```

## Misc. info

The project is running Vue 2 and Storybook v7. My pet theory at a glance is that this is a v7 specific issue.

**Comment by tobiasdiez** [comment]
Currently only Vue 3 is supported. The `parse` method from vue 2 returns a different result, namely
```ts
export declare interface SFCDescriptor {

    source: string;

    filename: string;

    template: SFCBlock | null;

    script: SFCScriptBlock | null;

    scriptSetup: SFCScriptBlock | null;

    styles: SFCBlock[];

    customBlocks: SFCCustomBlock[];

    cssVars: string[];

    errors: (string | WarningMessage)[];

    /**

     * compare with an existing descriptor to determine whether HMR should perform

     * a reload vs. re-render.

     *

     * Note: this comparison assumes the prev/next script are already identical,

     * and only checks the special case where `<script setup lang="ts">` unused

     * import pruning result changes due to template changes.

     */

    shouldForceReload: (prevImports: Record<string, ImportBinding>) => boolean;

}
```
(from https://www.npmjs.com/package/@vue/compiler-sfc/v/2.7.14?activeTab=code)

I fear I don't have the capacity right now to add support for vue2, but PRs are welcome. Starting point would be https://github.com/tobiasdiez/storybook-vue-addon/blob/47afeb6ed59122504fb35eea59ead192f05f8863/src/core/parser.ts#L23.

Alternatively, but I'm not sure if this works, we can remove the peer dependency on vue and replace it by a direct dependency on `@vue/compiler-sfc` v3.

**Comment by floroz** [comment]
[Vue 2 is reaching end of life in December 2023](https://v2.vuejs.org/lts/).

Considering this addon is in its infancy and the majority of the features to support Storybook CSF parity have not been implemented yet, it would make sense to lock `vue` in the peer at the version supported by the current parser `>= 3`.

**Comment by tobiasdiez** [comment]
I agree with @floroz. We currently have a peer dependency on `"vue": "^3.2.47"` (mostly because that's the oldest version I've tested it with). 

I'm closing this issue, but would accept PRs implementing vue 2 support if they are not too involved.
