### ISSUE TITLE
adding `<docs lang="md"></docs>`  fails without `@mdx-js/react` dependency explicitly installed

### ISSUE THREAD

**Issue by floroz** [tobiasdiez/storybook-vue-addon#66]
When creating a new Story, and adding a `<docs />` blog, an error is thrown:

```sh
11:35:16 AM [vite] Internal server error: Failed to resolve import "@mdx-js/react" from "src/components/b-button/b-button.stories.vue?vue&type=stories". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/floroz/Repository/brink/packages/brink-ui/src/components/b-button/b-button.stories.vue?vue&type=stories:25:57
  23 |  };
  24 |  
  25 |  import { useMDXComponents as _provideComponents } from "@mdx-js/react";
     |                                                          ^
  26 |  import { jsx as _jsx } from "react/jsx-runtime";
  27 |  import {
      at formatError (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:43944:46)
      at TransformContext.error (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:43940:19)
      at normalizeUrl (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:41754:33)
      at async file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:41898:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:41823:13)
      at async Object.transform (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:44234:30)
      at async loadAndTransform (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:54901:29)
      at async viteTransformMiddleware (file:///Users/floroz/Repository/brink/node_modules/.pnpm/vite@4.4.8_@types+node@18.17.0_sass@1.64.2/node_modules/vite/dist/node/chunks/dep-75f53616.js:64296:32)
```

Explicitly installing `@mdx-js/react` solves the issue.

**Comment by tobiasdiez** [comment]
This is strange, for me its pulled-in by the docs addon: https://github.com/tobiasdiez/storybook-vue-addon/blob/02839f9b53c304ec562f34df20d9bf7bc6aa4897/pnpm-lock.yaml#L2140

Maybe related to https://github.com/storybookjs/storybook/issues/19821?

**Comment by floroz** [comment]
> This is strange, for me its pulled-in by the docs addon:
> 
> https://github.com/tobiasdiez/storybook-vue-addon/blob/02839f9b53c304ec562f34df20d9bf7bc6aa4897/pnpm-lock.yaml#L2140
> 
> Maybe related to [storybookjs/storybook#19821](https://github.com/storybookjs/storybook/issues/19821)?

I need to check if I can reproduce it on a new `vite` project using `pnpm` as package manager and in a new `pnpm workspaces` / `vite` project.
